export const ITEMDETAIL_OPEN = "ITEMDETAIL_OPEN";
export const ITEMDETAIL_CLOSE = "ITEMDETAIL_CLOSE";
export const UPDATE_ITEM = "UPDATE_ITEM";
export const CIV_UPDATE = "CIV_UPDATE";
export const ITEMNAVBARTREEMOB_SELECTED = "ITEMNAVBARTREEMOB_SELECTED";
export const CHANGE_LOCALE = "CHANGE_LOCALE";
